apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# import the default deployment as the base
bases:
  - ../../operator/config/default
  - ../../klt-cert-manager/config/default
  - ../../scheduler/manifests/install
# replace the default namespace with {{ include "chart.namespace" . }}
# .Release.Namespace has not been used so that a custom _helpers.tpl file can maintain the expected behaviour of
# helm install -n
namespace: "{{ .Release.Namespace }}"
patchesStrategicMerge:
  - patches/patch_deployment.yaml
  - patches/patch_readylive.yaml


patches:
  #patch labels and images for all
  - patch: |
      - op: replace
        path: '/spec/template/spec/containers/0/imagePullPolicy'
        value: |-
          {{ .Values.global.imagePullPolicy}}
      - op: add
        path: '/spec/template/metadata/labels/automation'
        value: |-
            {{- if .Values.commonLabels }}
            {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 8 }}
            {{- end }}
            {{- if .Values.podLabels }}
            {{- include "common.tplvalues.render" ( dict "value" .Values.podLabels "context" $) | nindent 8 }}
            {{- end }}
    target:
      kind: Deployment
      name: "(controller-manager|cert-manager|keptn-scheduler)"

  # patches cert manager and operator since they already have annotations
  - patch: |
        - op: add
          path: '/spec/template/metadata/annotations/automation'
          value: |
            {{- if .Values.commonAnnotations }}
            {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 8 }}
            {{- end }}
            {{- if .Values.podAnnotations }}
            {{- include "common.tplvalues.render" ( dict "value" .Values.podAnnotations "context" $) | nindent 8 }}
            {{- end }}
    target:
      kind: Deployment
      name: "(controller-manager|cert-manager)"

  # patches when no annotations exist (for now this is true in scheduler)
  - patch: |
        - op: add
          path: '/spec/template/metadata/automation'
          value: |
            {{- if or .Values.podAnnotations .Values.commonAnnotations }}
            annotations:
              {{- if .Values.commonAnnotations }}
                {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 8 }}
                {{- end }}
                {{- if .Values.podAnnotations }}
                {{- include "common.tplvalues.render" ( dict "value" .Values.podAnnotations "context" $) | nindent 8 }}
                {{- end }}
            {{- end }}
    target:
      kind: Deployment
      name: "(keptn-scheduler)"